# https://wandb.ai

wandb:
  wandb_project_name: reactive_correction
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  offline: False
  id: null
  anonymous: null
  project: "r-clarc"
  log_model: False
  prefix: ""
  group: ""
  tags: []
  job_type: ""
